# Generated by Django 6.0.3 on 2026-03-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='courses',
            new_name='course',
        ),
    ]
