# Generated by Django 6.0.3 on 2026-03-26 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_instructor_alter_lesson_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='Learning_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Completed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='percentage_complete',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
