# Generated by Django 6.0.3 on 2026-03-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_progress_learning_status_progress_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='overall_progress',
            field=models.FloatField(default=0),
        ),
    ]
