# Generated by Django 6.0.3 on 2026-04-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_overall_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='Click the link to watch tutorial', null=True),
        ),
    ]
